# Generated by Django 5.2.6 on 2025-09-08 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImportedAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sku", models.CharField(db_index=True, max_length=64)),
                ("view", models.CharField(blank=True, max_length=32)),
                ("original_name", models.CharField(max_length=255)),
                ("stored_path", models.CharField(max_length=512)),
                ("status", models.CharField(default="queued", max_length=16)),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
